# Generated by Django 4.0.3 on 2022-03-21 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='blogpost',
            table='blog_post',
        ),
    ]
